Fix for #50
dotMorten/Microsoft.SqlServer.Types pull request #53
Opened 2020-10-08 05:31 UTC by yorek

Seems that support to Geometry binary format v2 is already there, but when reading the byte stream, the maximum expected version was still set to 1

2020-10-08 19:04 UTC, dotMorten requested changes
I don't think it's correct to just claim v2 support, without actually adding v2 support.
Also there's a huge amount of white space/newline changes in the PR

2020-10-08 19:04 UTC, dotMorten commented on src/Microsoft.SqlServer.Types/ShapeData.cs
> +        public const byte MAX_GEOGRAPHY_SERIALIZATION_FORMAT_SUPPORTED = 2;
That's not really the case though is it? The library currently does not support the curve segments that were added to v2

2020-10-08 19:46 UTC, yorek commented on src/Microsoft.SqlServer.Types/ShapeData.cs
> +        public const byte MAX_GEOGRAPHY_SERIALIZATION_FORMAT_SUPPORTED = 2;
Mmmm..the point that I have created (on Azure SQL) a POLYGON and still got a binary format that shows 2 as version, even if I'm not using curve segments. Without this hack/fix, the geography will not be handled correctly

2020-10-08 19:48 UTC, dotMorten commented on src/Microsoft.SqlServer.Types/ShapeData.cs
> +        public const byte MAX_GEOGRAPHY_SERIALIZATION_FORMAT_SUPPORTED = 2;
I don't know why it's serialized as v2 when not needed, but this library currently doesn't support v2, so it's correctly failing until #9 has been addressed.

2022-01-04 22:25 UTC, dotMorten commented
Closing this, since I'd rather we get proper v2 curve support before trying to read it

2022-01-04 22:25 UTC, closed without merging